name:                FOLParser
version:             0.1.0.0
github:              "lukeptyler/Automated-Theorem-Prover"
license:             BSD3
author:              "Luke Tyler"
copyright:           "2020 Luke Tyler"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at https://github.com/lukeptyler/Automated-Theorem-Prover#readme

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  FOLParser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FOLParser

tests:
  utility-tests:
    main:                Spec.hs
    source-dirs:         test/utility
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FOLParser
    - hspec
    - hspec-core
    - QuickCheck
  tableau-tests:
    main:                Spec.hs
    source-dirs:         test/tableau
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FOLParser
    - hspec
